Bongo/Bongo.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Bongo.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

    }
}

Bongo/Bongo.Web/Controllers/RoomBookingController.cs
using Bongo.Core.Services.IServices;
using Bongo.Models.Model;
using Bongo.Models.Model.VM;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bongo.Web.Controllers
{
    public class RoomBookingController : Controller
    {
        private IStudyRoomBookingService _studyRoomBookingService;

        public RoomBookingController(IStudyRoomBookingService studyRoomBookingService)
        {
            _studyRoomBookingService = studyRoomBookingService;
        }
        public IActionResult Index()
        {
            return View(_studyRoomBookingService.GetAllBooking());

        }
        public IActionResult Book()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Book(StudyRoomBooking studyRoomBooking)
        {
            IActionResult actionResult = View("Book");
            if (ModelState.IsValid)
            {
                var result = _studyRoomBookingService.BookStudyRoom(studyRoomBooking);
                if (result.Code == StudyRoomBookingCode.Success)
                {
                    actionResult = RedirectToAction("BookingConfirmation", result);
                }
                else if (result.Code == StudyRoomBookingCode.NoRoomAvailable)
                {
                    ViewData["Error"] = "No Study Room available for selected date";
                }
            }

            return actionResult;
        }
        public IActionResult BookingConfirmation(StudyRoomBookingResult studyRoomBooking)
        {
            return View(studyRoomBooking);
        }
    }
}

Bongo/Bongo.Web/Controllers/RoomsController.cs
using Bongo.Core.Services.IServices;
using Bongo.Models.Model;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bongo.Web.Controllers
{
    public class RoomsController : Controller
    {
        private readonly IStudyRoomService _studyRoomService;
        public RoomsController(IStudyRoomService studyRoomService)
        {
            _studyRoomService = studyRoomService;
        }
        public IActionResult Index()
        {
            return View(_studyRoomService.GetAll());
        }

       
    }
}

Bongo/Bongo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="card">
    <div class="card-header">
        Book Study Room
    </div>
    <div class="card-body">
        <p>
            Book a study room with ease :
        </p>
        <a asp-action="Book" asp-controller="RoomBooking" class="btn btn-primary">Book Study Room</a>
    </div>
</div>

Bongo/Bongo.Web/Views/RoomBooking/Book.cshtml
@model StudyRoomBooking

<h1 class="display-4">Book a Study Room</h1>
<p class="lead"> for a full day!</p>

<form method="post">

    <div class="form-group">
        <label asp-for="FirstName" class="control-label"></label>
        <input asp-for="FirstName" class="form-control">
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="LastName" class="control-label"></label>
        <input asp-for="LastName" class="form-control">
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control">
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Date" class="control-label"></label>
        <input asp-for="Date" asp-format="{0:dd/MM/yyyy}" class="form-control">
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>
    @if ((string)ViewData["Error"] != null) { 
        <p class="text-danger">
            @ViewData["Error"].ToString()
        </p>
    }
    <button type="submit" class="btn btn-primary">Book Study Room</button>

</form>
@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bongo/Bongo.Web/Views/RoomBooking/BookingConfirmation.cshtml
@model Bongo.Models.Model.VM.StudyRoomBookingResult
 
<h1 class="display-4">Your Study Room is booked</h1>
<p class="lead">
    for the whole day!
</p>
<p>
    Hi @Model.FirstName,
</p>
<p>
    A Study Room was booked for you
    on <strong>@Model.Date.ToShortDateString()</strong>.<br />
    Your booking number is <strong>@Model.BookingId</strong>.<br />
    
</p>


<div>
    <a class="btn-primary btn" style="margin-top: 25px"  asp-action="Book">Book another Study Room</a>
</div>

Bongo/Bongo.Web/Views/RoomBooking/Index.cshtml
@model IEnumerable<StudyRoomBooking> 
<h1 class="display-4">Study Room Bookings</h1>

<hr />

<table class="table table-striped table-bordered dt-responsive nowrap">
    <thead class="thead-light">
        <tr>
            <th>Date</th>
            <th>Booking Id</th>
            <th>Room ID</th>
            <th>Email</th>
            <th>FirstName</th>
            <th>LastName</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var booking in Model)
        {
        <tr>
            <td>@booking.Date.ToShortDateString()</td>
            <td>@booking.BookingId</td>
            <td>@booking.StudyRoomId</td>
            <td>@booking.Email</td>
            <td>@booking.FirstName</td>
            <td>@booking.LastName</td>
        </tr>}
    </tbody>
</table>

Bongo/Bongo.Web/Views/Rooms/Index.cshtml
@model IEnumerable<StudyRoom>

<br />
<div class="backgroundWhite">
            <h2 class="text-info"> Room List</h2>
    <br />
    <div>
        @if (Model.Count() > 0)
        {
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        Id
                    </th>
                    <th>
                        Room Number
                    </th>
                    <th>
                        Room Name
                    </th>
                   
                </tr>
                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.RoomNumber
                </td>
                <td>
                    @item.RoomName
                </td>
                
            </tr>
                }
            </table>
        }
        else
        {
            <p>No category exists...</p>
        }
    </div>
</div>

Bongo/Bongo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bongo.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bongo.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RoomBooking" asp-action="Index">Bookings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Bongo.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>